### PR TITLE
feat: Apply the requested fps

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
<details>
<summary>chore: Notify the visitor that they must view this demo using a web server</summary>

</details>

<details>
<summary>chore: Add fps counter</summary>

</details>

---

*Note that this PR does fix the issue explained in #1*

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
oh snap, I accidentally included a change in the c file, I'll revert that

**Comment by ArjixWasTaken** [comment]
*Note that this PR does not fix #1*

**Comment by rexim** [comment]
Thanks for the contribution! But please don't mash several things into a single PR! Separate this into two, so I can review them and test them separately. Thanks! (I'll add this to the contribution rules a bit later).

**Comment by ArjixWasTaken** [comment]
Sure!

**Pull request closed without merging**
